Makefile, Network/Makefile_Network.mk, Network/Tests/src/ClientList/tests_linked_list.c, Network/include/ClientList/client_list.h, Network/include/ErrorHandling/check_return_value.h, Network/include/Server/server.h, Network/src/ClientList/client_list.c, Network/src/ClientList/client_list_bis.c, Network/src/ErrorHandling/check_return_value.c, Network/src/ErrorHandling/return_error_str.c, Network/src/Server/server_loop.c, Network/src/Server/zappy_network.c, Network/src/main.c
Create base of the server.
To obtains more details, please see:
- #4
=> 4 create the base of the server

Network/Makefile_Network.mk, Network/Tests/src/ClientListTests/tests_linked_list.c, Network/Tests/src/ServerTests/init_in_game_stuct_test.c, Network/include/ClientList/client_list.h, Network/include/Server/server.h, Network/src/ClientList/client_list.c, Network/src/ClientList/client_list_bis.c, Network/src/ErrorHandling/check_return_value.c, Network/src/Parsing/move_args_to_struct.c, Network/src/Server/init_in_game_stuct.c, Network/src/Server/server_loop.c, Network/src/Server/zappy_network.c
see  #22.
the server and the client will start their comms as so:
<-- WELCOME \ n
--> TEAM - NAME \ n
<-- CLIENT - NUM \ n
<-- X Y \ n
atm this whole process is blocking...
=> :ticket: ai/server communication start

Network/Tests/src/ParsingTests/move_args_to_struct_test.c, Network/include/Game/game.h, Network/include/Server/server.h, Network/src/Game/game_functions.c, Network/src/Server/init_in_game_stuct.c, Network/src/Server/server_loop.c
ressources now spawn on Trantor !
/!\ for ressources to spawn correctly when picking/dropping items, the "picked_up_items" inventory_t structure should have it according ressources updated (+1\-1) /!\
=> :gem: resources system

AI/src/ai_zappy.py
Create all functions command  for Bot class.
There is repetitive code but i will fix it in another pull request
Function look is not completed
Functions can change with project evolution
Closes #15
=> 🔀 15 package create functions to get data from server

Network/include/Game/game.h, Network/include/Server/server.h, Network/src/Game/game_functions.c, Network/src/Server/init_in_game_stuct.c, Network/src/Server/server_loop.c, Network/src/Server/update_players.c
see #43 
our little guys now have to eat in order to survive. they start with the equivalent of 10 food in the stomach(1260 hp), and eat when they reach 0 if they have a piece of food in the inventory (gain 126 hp). they loose 1 hp each game tick.
i also changed how the server check how many trantorian are alive since the can die.
=> :poultry_leg: Trantorian can now eat (and would die if they dont)

Network/CMakeLists.txt, Network/Makefile_Network.mk, Network/include/Game/game_command.h, Network/include/Game/game_functions.h, Network/include/Server/server.h, Network/src/Game/egg_hatching.c, Network/src/Game/game_command.c, Network/src/Game/game_command_bis.c, Network/src/Game/game_functions.c, Network/src/Server/init_in_game_stuct.c
see #25 
commands:
Fork
Eject
Connect_nbr
are now implemented.
=> :three: life and death of a trantor

Network/Makefile_Network.mk, Network/include/Game/game.h, Network/include/Game/game_command.h, Network/include/Game/game_functions.h, Network/src/Game/game_command_bis.c, Network/src/Game/game_command_ter.c, Network/src/Game/inventory_function.c, Network/src/Game/look_around.c, Network/src/Game/object_manipulation.c
To obtain more details, please see:
- #26
=> 4️⃣  In game object interaction

README.md
creating a README.md file at the root of the project explaining every command
=> :bulb: Create README.md

Network/src/Server/server_loop.c
see
- #71 
pretty self explanatory
=> :bug: AI-server communication

Network/src/GUI/player_info_cmd.c
To see more detail, please take a site and a beer to take a good time with this:
- #54
=> :video_game: Create the player info command

Network/src/GUI/time_cmd.c
To see more details please take a look at:
- #56
=> :sparkles: Create time command function

AI/src/ai_zappy.py
Add result management to Bot class
Add look function to update the Bot map
Algorithm to grow up level 2 not working
Closes :
- #76
=> :sparkles:  Add result managment

Network/include/GuiProtocol/gui.h, Network/include/GuiProtocol/gui_event.h, Network/src/Game/game_functions.c, Network/src/Game/object_manipulation.c, Network/src/GuiProtocol/game_info_cmd.c, Network/src/GuiProtocol/player_info_cmd.c, Network/src/GuiProtocol/time_cmd.c, Network/src/Server/server_loop.c
forward now go in the correct direction
Respawn of items is now correctly done
=> :bug: Fixed commands

Network/src/Server/server_loop.c
to have more detail, take a close attention to:
- #86
=> :bug: Fix server loop bug

AI/src/ai_zappy.py, AI/src/client_module.py
Fix table creation from results in look function
Fix adding objects in map variable
Closes :
- #84
=> :bug: Fix AI's Look function

AI/src/ai_zappy.py, AI/src/parsing.py
Use `popen` instead of `subprocess`, so that the process is "non-blocking" and allow to go through the loop.
=> 🥚 Update fork way using popen instead of subprocess

GUI/Makefile_GUI.mk, GUI/src/core/Core.cpp, GUI/src/core/Core.hpp, GUI/src/main.cpp
The objectiv is to create a Core function to cleanify the main function.
```mermaid
graph TD;
Irrlicht --> client
Irrlicht --> chessboard
chessboard --> client
client --> service
service --> client
chessboard --> Event_handler
Event_handler --> client
Irrlicht --> Zappygame
Zappygame --> Core
Core --> Main
Zappygame --> chessboard
Zappygame --> team
Zappygame --> player
team --> player_pos
player --> player_pos
player --> chess_piece
chess_piece --> player_pos
chess_piece --> Event_handler
```
=> :twisted_rightwards_arrows: Migrate core

Network/src/Game/launch_broadcast.c, Network/src/Server/update_players.c
And write a special case for broadcast function because in it, there is just one argument, but in it, it can have space.
=> :bug: Fix argument function

Network/CMakeLists.txt, Network/Makefile_Network.mk, Network/include/Game/game.h, Network/include/GuiProtocol/gui.h, Network/include/GuiProtocol/gui_event.h, Network/src/Game/game_functions.c, Network/src/Game/incantation.c, Network/src/Game/launch_broadcast.c, Network/src/GuiProtocol/gui_event.c, Network/src/GuiProtocol/gui_event_quin.c, Network/src/GuiProtocol/start_gui_client.c, Network/src/Server/complete_server.c, Network/src/Server/server_loop.c, Network/src/Server/update_players.c, Network/src/Server/zappy_network.c
see
- #105 
it is really just a bunch of adjustments i detailed in the linked issue up here.
=> :bookmark: tabs server adjustement

GUI/src/networkGui/guiClient.cpp
To have more info look:
- #111
=> 👂 add socket listener

AI/src/ai_zappy.py, AI/src/client_module.py, Network/src/Game/launch_broadcast.c, Network/src/Server/update_players.c
first pawn to spawn will be considered the queen.
he will broadcast to all other pawns.
once everyone have foods to survive and are lvl 2 they will find the queen location and note it
=> :crown: pawn will find their queen

GUI/interface/AError.hpp, GUI/interface/IError.hpp, GUI/src/chessElement/chessBoard.cpp, GUI/src/chessElement/chessBoard.hpp, GUI/src/core/Core.cpp, GUI/src/event/irrlichtEventHandler.cpp, GUI/src/event/irrlichtEventHandler.hpp, GUI/src/event/serverDataReceiver.cpp, GUI/src/event/serverDataReceiver.hpp, GUI/src/game/ZappyGame.cpp, GUI/src/game/ZappyGame.hpp, GUI/src/loader/objLoader.cpp, GUI/src/loader/objLoader.hpp, GUI/src/loader/textureLoader.cpp, GUI/src/loader/textureLoader.hpp, GUI/src/networkGui/guiClient.cpp, GUI/src/networkGui/guiClient.hpp, GUI/src/player/player.cpp, GUI/src/player/player.hpp, GUI/src/player/team.cpp, GUI/src/player/team.hpp, GUI/src/zappyIrrlicht/irrlichtWindow.cpp, GUI/src/zappyIrrlicht/irrlichtWindow.hpp, Makefile
To have more info look:
- #101
=> :rotating_light: Cleanify error handling

AI/src/ai_zappy.py
Complete other function in Bot class and add take_everything_on_tile calling in queen function
closes:
- #118
=> :sparkles: Complete AI's 'other' mode

GUI/src/event/serverDataReceiver.cpp, GUI/src/game/ZappyGame.cpp, GUI/src/networkGui/guiClient.cpp, GUI/src/player/player.cpp, GUI/src/zappyIrrlicht/irrlichtWindow.cpp, Makefile
In this pull request, i've done the update of all the players, now they can move and rotate.
=> :godmode: Update keyboard input

GUI/src/networkGui/guiClient.cpp, GUI/src/zappyIrrlicht/irrlichtWindow.cpp, GUI/src/zappyIrrlicht/irrlichtWindow.hpp
Add error handling to leave properly the GUI when ctrl+C the server.
=> :twisted_rightwards_arrows: Cleanify error handling

GUI/src/event/irrlichtEventHandler.cpp, GUI/src/event/irrlichtEventHandler.hpp, GUI/src/event/serverDataReceiver.cpp, GUI/src/game/ZappyGame.cpp, GUI/src/game/ZappyGame.hpp, GUI/src/items/tiles.cpp, GUI/src/networkGui/guiClient.cpp, GUI/src/player/player.cpp, GUI/src/player/playerPosition.cpp, GUI/src/zappyIrrlicht/irrlichtWindow.cpp
I fix a issue when a player die during a call with the gui.
=> :bug: Handle player death

GUI/src/chessElement/chessBoard.cpp, GUI/src/chessElement/chessPiece.cpp, GUI/src/core/Core.cpp, GUI/src/event/irrlichtEventHandler.cpp, GUI/src/event/irrlichtEventHandler.hpp, GUI/src/game/ZappyGame.cpp, GUI/src/networkGui/guiClient.cpp, GUI/src/player/player.cpp, GUI/src/zappyIrrlicht/irrlichtWindow.cpp, GUI/src/zappyIrrlicht/irrlichtWindow.hpp
When hit escape key, send quit message to the server.
=> 🚪🚶Escape corretly

GUI/src/chessElement/chessBoard.cpp, GUI/src/chessElement/chessPiece.cpp, GUI/src/core/Core.cpp, GUI/src/event/irrlichtEventHandler.cpp, GUI/src/event/irrlichtEventHandler.hpp, GUI/src/game/ZappyGame.cpp, GUI/src/networkGui/guiClient.cpp, GUI/src/player/player.cpp, GUI/src/zappyIrrlicht/irrlichtWindow.cpp
=> :bug: Fix memory leak
